
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manolo96
 */
public class Pantalla extends javax.swing.JFrame {

    
    private Graphics g;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        g = pColoreado.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRadioBotones = new javax.swing.ButtonGroup();
        pCentral = new javax.swing.JPanel();
        pBotones = new javax.swing.JPanel();
        rbRojo = new javax.swing.JRadioButton();
        rbVerde = new javax.swing.JRadioButton();
        rbAzul = new javax.swing.JRadioButton();
        rbAmarillo = new javax.swing.JRadioButton();
        rbPersonalizado = new javax.swing.JRadioButton();
        pColoreado = new javax.swing.JPanel();
        mBarraherramientas = new javax.swing.JMenuBar();
        mMenu = new javax.swing.JMenu();
        miInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pCentral.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pBotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pBotones.setLayout(new java.awt.GridLayout(5, 0));

        bgRadioBotones.add(rbRojo);
        rbRojo.setText("Rojo");
        rbRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRojoActionPerformed(evt);
            }
        });
        pBotones.add(rbRojo);

        bgRadioBotones.add(rbVerde);
        rbVerde.setText("Verde");
        rbVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerdeActionPerformed(evt);
            }
        });
        pBotones.add(rbVerde);

        bgRadioBotones.add(rbAzul);
        rbAzul.setText("Azul");
        rbAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAzulActionPerformed(evt);
            }
        });
        pBotones.add(rbAzul);

        bgRadioBotones.add(rbAmarillo);
        rbAmarillo.setText("Amarillo");
        rbAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmarilloActionPerformed(evt);
            }
        });
        pBotones.add(rbAmarillo);

        bgRadioBotones.add(rbPersonalizado);
        rbPersonalizado.setText("Personalizado");
        rbPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPersonalizadoActionPerformed(evt);
            }
        });
        pBotones.add(rbPersonalizado);

        pCentral.add(pBotones);

        pColoreado.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout pColoreadoLayout = new javax.swing.GroupLayout(pColoreado);
        pColoreado.setLayout(pColoreadoLayout);
        pColoreadoLayout.setHorizontalGroup(
            pColoreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pColoreadoLayout.setVerticalGroup(
            pColoreadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        pCentral.add(pColoreado);

        getContentPane().add(pCentral, java.awt.BorderLayout.CENTER);

        mMenu.setText("Sobre");

        miInformacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        miInformacion.setText("Información");
        miInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInformacionActionPerformed(evt);
            }
        });
        mMenu.add(miInformacion);

        mBarraherramientas.add(mMenu);

        setJMenuBar(mBarraherramientas);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Pone el color del panel verde
     * @param evt 
     */
    private void rbVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerdeActionPerformed
        
        g.setColor(Color.green);
        g.fillRect(0,0,this.getWidth(),this.getHeight());
    }//GEN-LAST:event_rbVerdeActionPerformed

    /**
     * Pone el color del panel rojo
     * @param evt 
     */
    private void rbRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRojoActionPerformed
        g.setColor(Color.red);
        g.fillRect(0,0,this.getWidth(),this.getHeight());
        
    }//GEN-LAST:event_rbRojoActionPerformed

    /**
     * Pone el color del panel azul
     * @param evt 
     */
    private void rbAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAzulActionPerformed
        g.setColor(Color.blue);
        g.fillRect(0,0,this.getWidth(),this.getHeight());
    }//GEN-LAST:event_rbAzulActionPerformed

    /**
     * Pone el color del panel amarillo
     * @param evt 
     */
    private void rbAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmarilloActionPerformed
        g.setColor(Color.yellow);
        g.fillRect(0,0,this.getWidth(),this.getHeight());
    }//GEN-LAST:event_rbAmarilloActionPerformed

    /**
     * Nos muestra una ventana con todos los colores para elegir nosotros el que queramos
     * @param evt 
     */
    private void rbPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPersonalizadoActionPerformed
        Color ventana = JColorChooser.showDialog(this,"Seleccione un color", Color.white);
        
        pColoreado.setBackground(ventana);
    }//GEN-LAST:event_rbPersonalizadoActionPerformed

    /**
     * Botón que nos muestra una ventana de información
     * @param evt 
     */
    private void miInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInformacionActionPerformed
        
        String icono="<html><body><p><img src=https://eliademy.com/extimg/7c18aafa32_course_logo.jpg></img></p></body></html>";
        
        JOptionPane.showMessageDialog(this, 
        "Alumno: Manuel Muñoz Rodríguez"
                + "\nCurso: 2016-2017"
                + "\nReto: Ejercicio de clase III-Tema 8"
                + "\nPONIENTE FORMACIÓN"
                +"\n"+icono);
        
        
    }//GEN-LAST:event_miInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRadioBotones;
    private javax.swing.JMenuBar mBarraherramientas;
    private javax.swing.JMenu mMenu;
    private javax.swing.JMenuItem miInformacion;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCentral;
    private javax.swing.JPanel pColoreado;
    private javax.swing.JRadioButton rbAmarillo;
    private javax.swing.JRadioButton rbAzul;
    private javax.swing.JRadioButton rbPersonalizado;
    private javax.swing.JRadioButton rbRojo;
    private javax.swing.JRadioButton rbVerde;
    // End of variables declaration//GEN-END:variables
}
